#!/usr/bin/env node
// Regenerates the AUTO-GENERATED sections of the documentation.
// Only the text between a BEGIN/END marker pair is rewritten; everything else
// in the file is left exactly as it is. Running it twice gives the same result.
//
//   <!-- BEGIN GENERATED: env-vars -->   (do not edit by hand)
//   <!-- END GENERATED: env-vars -->
//
// Generators:
//   env-vars  table from config/env.schema.json: a JSON Schema exported from the
//             zod env schema by scripts/export-env-schema.ts (npm run docs:env-schema).
//             Fails if the file is missing, or stale: the export records the
//             SHA-256 of its zod source file (x-source, x-source-sha256).
//   commands  table from package.json "scripts" (+ optional "scriptsInfo" descriptions)
//
// Usage: node scripts/generate-docs.mjs           rewrite stale sections
//        node scripts/generate-docs.mjs --check   exit 1 if any section is stale
// No dependencies, no network.
import { createHash } from 'node:crypto';
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = process.cwd();
const CHECK = process.argv.includes('--check');
const SCAN = ['README.md', 'docs'];
const MARKER = /<!-- BEGIN GENERATED: ([a-z0-9-]+) -->\n([\s\S]*?)<!-- END GENERATED: \1 -->/g;
const NOTE = '<!-- Generated by scripts/generate-docs.mjs. Do not edit inside these markers. -->';
const ENV_SCHEMA = 'config/env.schema.json';
const EXPORT_CMD = 'npm run docs:env-schema';

const cell = (v) => String(v ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
// One table row; empty cells become "| |" to match the repository's table style.
const row = (cells) => `|${cells.map((c) => (c === '' ? ' ' : ` ${c} `)).join('|')}|`;

// Same normalisation as the export script, so CRLF checkouts hash the same.
const sourceHash = (file) => createHash('sha256').update(readFileSync(file, 'utf8').replace(/\r\n/g, '\n')).digest('hex');

function readEnvSchema() {
  const full = join(ROOT, ENV_SCHEMA);
  if (!existsSync(full)) {
    throw new Error(`${ENV_SCHEMA} is missing. Export it from the zod env schema: ${EXPORT_CMD}`);
  }
  const schema = JSON.parse(readFileSync(full, 'utf8'));
  const source = schema['x-source'];
  if (!source || !schema['x-source-sha256']) {
    throw new Error(`${ENV_SCHEMA} has no x-source / x-source-sha256 fields, so it cannot be checked. Re-export it: ${EXPORT_CMD}`);
  }
  const src = join(ROOT, source);
  if (!existsSync(src)) throw new Error(`${ENV_SCHEMA} refers to ${source}, which does not exist. Re-export it: ${EXPORT_CMD}`);
  if (sourceHash(src) !== schema['x-source-sha256']) {
    throw new Error(`${ENV_SCHEMA} is stale: ${source} changed after the last export. Run: ${EXPORT_CMD}, then node scripts/generate-docs.mjs`);
  }
  return schema;
}

function readJson(path) {
  const full = join(ROOT, path);
  if (!existsSync(full)) throw new Error(`source not found: ${path}`);
  return JSON.parse(readFileSync(full, 'utf8'));
}

const generators = {
  'env-vars': () => {
    const schema = readEnvSchema();
    const props = schema.properties || {};
    const required = new Set(schema.required || []);
    const rows = Object.keys(props).sort().map((name) => {
      const p = props[name];
      const secret = p['x-secret'] === true;
      const def = secret ? '(from Secrets Manager / SSM)' : p.default === undefined ? '' : `\`${typeof p.default === 'string' ? p.default : JSON.stringify(p.default)}\``;
      return row([`\`${cell(name)}\``, required.has(name) ? 'yes' : 'no', cell(def), secret ? 'yes' : 'no', cell(p.description)]);
    });
    return ['| Variable | Required | Default | Secret | Description |', '| --- | --- | --- | --- | --- |', ...rows];
  },
  commands: () => {
    const pkg = readJson('package.json');
    const info = pkg.scriptsInfo || {};
    const names = Object.keys(pkg.scripts || {}).sort();
    const rows = names.map((n) => row([`\`npm run ${cell(n)}\``, `\`${cell(pkg.scripts[n])}\``, cell(info[n])]));
    return ['| Command | Runs | Description |', '| --- | --- | --- |', ...rows];
  }
};

function files() {
  const out = [];
  const walk = (p) => {
    if (!existsSync(p)) return;
    if (statSync(p).isDirectory()) {
      for (const name of readdirSync(p)) if (name !== 'node_modules') walk(join(p, name));
    } else if (p.endsWith('.md')) out.push(p);
  };
  for (const entry of SCAN) walk(join(ROOT, entry));
  return out.sort();
}

let stale = 0;
let errors = 0;
for (const file of files()) {
  const text = readFileSync(file, 'utf8');
  const next = text.replace(MARKER, (whole, name) => {
    const gen = generators[name];
    if (!gen) {
      errors += 1;
      console.error(`${relative(ROOT, file)}: unknown generated section "${name}"`);
      return whole;
    }
    try {
      const body = [NOTE, '', ...gen(), '', ''].join('\n');
      return `<!-- BEGIN GENERATED: ${name} -->\n${body}<!-- END GENERATED: ${name} -->`;
    } catch (err) {
      errors += 1;
      console.error(`${relative(ROOT, file)}: section "${name}": ${err.message}`);
      return whole;
    }
  });
  if (next !== text) {
    stale += 1;
    if (CHECK) console.error(`stale: ${relative(ROOT, file)}`);
    else {
      writeFileSync(file, next);
      console.log(`updated: ${relative(ROOT, file)}`);
    }
  }
}

if (errors) process.exit(1);
if (CHECK && stale) {
  console.error('\nGenerated documentation is out of date. Run:\n  node scripts/generate-docs.mjs\nand commit the result.');
  process.exit(1);
}
console.log(CHECK ? 'PASS: generated sections are up to date.' : `done (${stale} file(s) updated).`);
